// Package cert generates the Certificate of Completion PDF for a completed
// signing envelope. It uses the pure-Go github.com/go-pdf/fpdf library so the
// service has no native (C) PDF dependency.
//
// Tier-1 scope: the certificate is a human + machine readable summary of the
// signing ceremony (document identity + content hash, every signer with
// timestamps / IP / user-agent / consent, and the final chained hash). It is
// NOT a PAdES/PKI-signed PDF — see the service docs for the Tier-2 deferral.
package cert

import (
	"bytes"
	"fmt"
	"time"

	"github.com/go-pdf/fpdf"
	"github.com/google/uuid"

	"github.com/pmplatform/services/document-svc/internal/domain"
)

// Data is the input to certificate generation.
type Data struct {
	DocumentTitle string
	DocumentID    string
	EnvelopeID    string
	ContentHash   string // canonical hash of the signed document version body
	FinalHash     string // final chained hash of the envelope
	CompletedAt   time.Time
	Signers       []domain.Signer
	Events        []domain.SignEvent
	// AuthEvidence maps signature-row id → step-up identity proof (e.g.
	// email OTP); rendered as "Identity verified: Email OTP verified at …".
	AuthEvidence map[string]domain.AuthEvidence
	// TSA maps signature-row id → RFC 3161 trusted-timestamp detail
	// (cert/tsa.go); rendered as a "Timestamp authority" line per signer.
	TSA map[uuid.UUID]TSALine
}

// Generate renders the Certificate of Completion and returns PDF bytes.
func Generate(d Data) ([]byte, error) {
	pdf := fpdf.New("P", "mm", "A4", "")
	pdf.SetMargins(18, 18, 18)
	pdf.SetAutoPageBreak(true, 18)
	pdf.AddPage()

	// Header
	pdf.SetFont("Helvetica", "B", 18)
	pdf.CellFormat(0, 10, "Certificate of Completion", "", 1, "L", false, 0, "")
	pdf.SetFont("Helvetica", "", 9)
	pdf.SetTextColor(110, 110, 110)
	pdf.CellFormat(0, 6, "Electronic signature record - Tier 1 (ESIGN / UETA / TH ETA)", "", 1, "L", false, 0, "")
	pdf.SetTextColor(0, 0, 0)
	pdf.Ln(3)
	drawRule(pdf)
	pdf.Ln(3)

	// Document identity
	section(pdf, "Document")
	kv(pdf, "Title", nz(d.DocumentTitle))
	kv(pdf, "Document ID", d.DocumentID)
	kv(pdf, "Envelope ID", d.EnvelopeID)
	kv(pdf, "Completed", d.CompletedAt.UTC().Format(time.RFC3339))
	kvMono(pdf, "Content hash (SHA-256)", d.ContentHash)
	kvMono(pdf, "Final chained hash", d.FinalHash)
	pdf.Ln(2)

	// Signers
	section(pdf, fmt.Sprintf("Signers (%d)", len(d.Signers)))
	for i, s := range d.Signers {
		pdf.SetFont("Helvetica", "B", 10)
		name := s.SignerName
		if name == "" {
			name = s.TypedName
		}
		if name == "" {
			name = s.SignerEmail
		}
		pdf.CellFormat(0, 6, fmt.Sprintf("%d. %s", i+1, nz(name)), "", 1, "L", false, 0, "")
		pdf.SetFont("Helvetica", "", 9)
		kv(pdf, "  Email", nz(s.SignerEmail))
		kv(pdf, "  Signer ID", s.SignerID.String())
		kv(pdf, "  Status", string(s.Status))
		kv(pdf, "  Auth method", string(s.AuthMethod))
		if ev, ok := d.AuthEvidence[s.ID.String()]; ok && ev.Method == string(domain.AuthEmailOTP) {
			kv(pdf, "  Identity verified", "Email OTP verified at "+ev.VerifiedAt.UTC().Format(time.RFC3339))
		}
		kv(pdf, "  Consent to electronic records", boolStr(s.Consent))
		if s.SignedAt != nil {
			kv(pdf, "  Signed at", s.SignedAt.UTC().Format(time.RFC3339))
		}
		if s.ViewedAt != nil {
			kv(pdf, "  First viewed", s.ViewedAt.UTC().Format(time.RFC3339))
		}
		ip, ua := lastSignerIPUA(d.Events, s.SignerID)
		if ip != "" {
			kv(pdf, "  IP address", ip)
		}
		if ua != "" {
			kvWrap(pdf, "  User agent", ua)
		}
		if s.ChainedHash != "" {
			kvMono(pdf, "  Chained hash", s.ChainedHash)
		}
		if t, ok := d.TSA[s.ID]; ok {
			kv(pdf, "  Timestamp authority", t.Line())
		}
		pdf.Ln(1)
	}

	// Audit trail
	pdf.Ln(1)
	section(pdf, fmt.Sprintf("Audit Trail (%d events)", len(d.Events)))
	pdf.SetFont("Helvetica", "", 8)
	for _, ev := range d.Events {
		line := fmt.Sprintf("%s  %-10s  ip=%s", ev.CreatedAt.UTC().Format(time.RFC3339), ev.EventType, nz2(ev.IPAddress, "-"))
		pdf.CellFormat(0, 5, line, "", 1, "L", false, 0, "")
	}

	pdf.Ln(4)
	drawRule(pdf)
	pdf.SetFont("Helvetica", "I", 8)
	pdf.SetTextColor(110, 110, 110)
	pdf.MultiCell(0, 4,
		"This certificate is a tamper-evident summary generated by the platform e-signature service. "+
			"The chained hash binds each signature to the exact document content at signing time; any later "+
			"modification of the document body invalidates chain verification.", "", "L", false)
	pdf.SetTextColor(0, 0, 0)

	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func section(pdf *fpdf.Fpdf, title string) {
	pdf.SetFont("Helvetica", "B", 12)
	pdf.CellFormat(0, 8, title, "", 1, "L", false, 0, "")
	pdf.SetFont("Helvetica", "", 9)
}

func kv(pdf *fpdf.Fpdf, k, v string) {
	pdf.SetFont("Helvetica", "B", 9)
	pdf.CellFormat(60, 5, k, "", 0, "L", false, 0, "")
	pdf.SetFont("Helvetica", "", 9)
	pdf.CellFormat(0, 5, v, "", 1, "L", false, 0, "")
}

func kvWrap(pdf *fpdf.Fpdf, k, v string) {
	pdf.SetFont("Helvetica", "B", 9)
	pdf.CellFormat(60, 5, k, "", 0, "L", false, 0, "")
	pdf.SetFont("Helvetica", "", 8)
	pdf.MultiCell(0, 5, v, "", "L", false)
}

func kvMono(pdf *fpdf.Fpdf, k, v string) {
	pdf.SetFont("Helvetica", "B", 9)
	pdf.CellFormat(60, 5, k, "", 0, "L", false, 0, "")
	pdf.SetFont("Courier", "", 7)
	pdf.MultiCell(0, 5, v, "", "L", false)
	pdf.SetFont("Helvetica", "", 9)
}

func drawRule(pdf *fpdf.Fpdf) {
	x, y := pdf.GetXY()
	pdf.SetDrawColor(200, 200, 200)
	pdf.Line(x, y, 192, y)
	pdf.SetDrawColor(0, 0, 0)
}

func boolStr(b bool) string {
	if b {
		return "Yes"
	}
	return "No"
}

func nz(s string) string {
	if s == "" {
		return "(untitled)"
	}
	return s
}

func nz2(s, def string) string {
	if s == "" {
		return def
	}
	return s
}

// lastSignerIPUA returns the IP/UA from the signer's most recent 'signed'
// event (falling back to any event by that signer).
func lastSignerIPUA(events []domain.SignEvent, signerID interface{ String() string }) (string, string) {
	var ip, ua string
	sid := signerID.String()
	for _, ev := range events {
		if ev.SignerID == nil || ev.SignerID.String() != sid {
			continue
		}
		if ev.IPAddress != "" {
			ip = ev.IPAddress
		}
		if ev.UserAgent != "" {
			ua = ev.UserAgent
		}
		if ev.EventType == domain.EvSigned {
			// prefer the signing event's values
			if ev.IPAddress != "" {
				ip = ev.IPAddress
			}
			if ev.UserAgent != "" {
				ua = ev.UserAgent
			}
		}
	}
	return ip, ua
}
