{{- if .Values.global.externalSecretsEnabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-credentials
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.global.secretStore | default "vault-backend" }}
    kind: ClusterSecretStore
  target:
    name: platform-credentials
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: {{ .Values.global.vaultPath | default "secret/platform" }}
        property: DATABASE_URL
    - secretKey: JWT_SECRET
      remoteRef:
        key: {{ .Values.global.vaultPath | default "secret/platform" }}
        property: JWT_SECRET
    - secretKey: SMTP_PASSWORD
      remoteRef:
        key: {{ .Values.global.vaultPath | default "secret/platform" }}
        property: SMTP_PASSWORD
{{- end }}
