{{- if .Values.identity.enabled -}}
{{- $svc := "identity-svc" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "platform.fullname" (dict "ctx" . "svc" $svc) }}
  labels:
    {{- include "platform.serviceLabels" (dict "ctx" . "svc" $svc) | nindent 4 }}
spec:
  type: {{ .Values.identity.service.type | default "ClusterIP" }}
  ports:
    - name: http
      port: {{ .Values.identity.service.port }}
      targetPort: {{ .Values.identity.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "platform.selectorLabels" (dict "ctx" . "svc" $svc) | nindent 4 }}
{{- end }}
