-- +goose Up

-- Tier-1 e-signature hardening (security review follow-up):
--
-- 1. Event-level hash chain: document_sign_event gains prev_event_hash /
--    event_hash so the audit trail itself is tamper-evident. Columns are
--    nullable — legacy rows inserted before this migration carry NULL and
--    verification reports them as "legacy" instead of failing.
--    A monotonic seq column makes chain ordering deterministic even when
--    two events share a µs-truncated created_at.
--
-- 2. Ed25519 record signing: each signature record's chained_hash is signed
--    with a platform key so a DB-write attacker cannot silently recompute the
--    whole SHA-256 chain. document_signature gains record_sig / record_kid;
--    keys live in document_sign_key (platform-level, NOT tenant-scoped —
--    same posture as identity-svc's signing_key table, hence no tenant_id
--    and no RLS).

ALTER TABLE document_sign_event ADD COLUMN prev_event_hash text;
ALTER TABLE document_sign_event ADD COLUMN event_hash text;
ALTER TABLE document_sign_event ADD COLUMN seq bigint GENERATED BY DEFAULT AS IDENTITY;
CREATE INDEX doc_sign_event_env_seq_idx ON document_sign_event(tenant_id, envelope_id, seq);

ALTER TABLE document_signature ADD COLUMN record_sig text NOT NULL DEFAULT '';
ALTER TABLE document_signature ADD COLUMN record_kid text NOT NULL DEFAULT '';

CREATE TABLE document_sign_key (
    kid         text PRIMARY KEY,
    public_key  text NOT NULL,  -- base64 (std) raw ed25519 public key (32 bytes)
    private_key text NOT NULL,  -- base64 (std) raw ed25519 private key (64 bytes)
    active      boolean NOT NULL DEFAULT true,
    created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX doc_sign_key_active_idx ON document_sign_key(active, created_at);

-- +goose Down

DROP TABLE IF EXISTS document_sign_key;

ALTER TABLE document_signature DROP COLUMN IF EXISTS record_kid;
ALTER TABLE document_signature DROP COLUMN IF EXISTS record_sig;

DROP INDEX IF EXISTS doc_sign_event_env_seq_idx;
ALTER TABLE document_sign_event DROP COLUMN IF EXISTS seq;
ALTER TABLE document_sign_event DROP COLUMN IF EXISTS event_hash;
ALTER TABLE document_sign_event DROP COLUMN IF EXISTS prev_event_hash;
