-- +goose Up

-- 1. metadata column on document
ALTER TABLE document ADD COLUMN metadata JSONB NOT NULL DEFAULT '{}'::jsonb;

-- 2. Allow null tenant_id on document_template (system templates have tenant_id = NULL)
ALTER TABLE document_template ALTER COLUMN tenant_id DROP NOT NULL;

-- 3. Drop old unique constraint (doesn't handle NULLs well), add partial ones
ALTER TABLE document_template DROP CONSTRAINT document_template_tenant_id_type_name_key;
CREATE UNIQUE INDEX template_tenant_type_name_uniq ON document_template(tenant_id, type, name) WHERE tenant_id IS NOT NULL;
CREATE UNIQUE INDEX template_system_type_name_uniq ON document_template(type, name) WHERE tenant_id IS NULL;

-- 4. RLS: allow system templates (tenant_id IS NULL) to be visible to all
DROP POLICY template_tenant_isolation ON document_template;
CREATE POLICY template_tenant_isolation ON document_template
    USING (tenant_id IS NULL OR tenant_id = current_tenant_uuid());

-- 5. Seed system templates
INSERT INTO document_template (id, tenant_id, type, name, body, is_system) VALUES
(gen_random_uuid(), NULL, 'brd', 'Standard BRD', '{"type":"doc","content":[{"type":"heading","attrs":{"level":1},"content":[{"type":"text","text":"Business Requirements Document"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"1. Executive Summary"}]},{"type":"paragraph","content":[{"type":"text","text":"[Describe the business need and proposed solution]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"2. Business Requirements"}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"BR-001: "}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"3. Constraints & Assumptions"}]},{"type":"paragraph","content":[{"type":"text","text":"[List constraints and assumptions]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"4. Out of Scope"}]},{"type":"paragraph","content":[{"type":"text","text":"[Explicitly list items that are out of scope]"}]}]}', true),
(gen_random_uuid(), NULL, 'frd', 'Standard FRD', '{"type":"doc","content":[{"type":"heading","attrs":{"level":1},"content":[{"type":"text","text":"Functional Requirements Document"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"1. Functional Requirements"}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"FR-001: The system shall..."}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"2. Non-Functional Requirements"}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"NFR-001: Performance - "}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"3. Acceptance Criteria"}]},{"type":"paragraph","content":[{"type":"text","text":"[Overall acceptance criteria for this document]"}]}]}', true),
(gen_random_uuid(), NULL, 'user_story', 'Standard User Story', '{"type":"doc","content":[{"type":"heading","attrs":{"level":1},"content":[{"type":"text","text":"User Story"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Description"}]},{"type":"paragraph","content":[{"type":"text","text":"(See structured cover fields above for As a / I want / So that)"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Notes & Attachments"}]},{"type":"paragraph","content":[{"type":"text","text":"[Additional context, wireframes, or references]"}]}]}', true),
(gen_random_uuid(), NULL, 'use_case', 'Standard Use Case', '{"type":"doc","content":[{"type":"heading","attrs":{"level":1},"content":[{"type":"text","text":"Use Case"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Basic Flow"}]},{"type":"orderedList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Step 1: "}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Alternative Flows"}]},{"type":"paragraph","content":[{"type":"text","text":"Alt 1A: [Condition] - [Steps]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Exception Flows"}]},{"type":"paragraph","content":[{"type":"text","text":"Exc 1A: [Error condition] - [System response]"}]}]}', true),
(gen_random_uuid(), NULL, 'process_flow', 'Standard Process Flow', '{"type":"doc","content":[{"type":"heading","attrs":{"level":1},"content":[{"type":"text","text":"Process Flow"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Process Steps"}]},{"type":"orderedList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Step description]"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Decision Points"}]},{"type":"paragraph","content":[{"type":"text","text":"[List decision points and outcomes]"}]}]}', true),
(gen_random_uuid(), NULL, 'rtm', 'Requirements Traceability Matrix', '{"type":"doc","content":[{"type":"heading","attrs":{"level":1},"content":[{"type":"text","text":"Requirements Traceability Matrix"}]},{"type":"paragraph","content":[{"type":"text","text":"Use the RTM panel below to link requirements to user stories and test references."}]}]}', true),
(gen_random_uuid(), NULL, 'sdd', 'Standard SDD', '{"type":"doc","content":[{"type":"heading","attrs":{"level":1},"content":[{"type":"text","text":"Software Design Document"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"1. System Overview"}]},{"type":"paragraph","content":[{"type":"text","text":"[High-level description of the system]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"2. Component Design"}]},{"type":"paragraph","content":[{"type":"text","text":"[Describe each major component]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"3. Data Flow"}]},{"type":"paragraph","content":[{"type":"text","text":"[Describe how data flows through the system]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"4. Security Considerations"}]},{"type":"paragraph","content":[{"type":"text","text":"[Auth, authorization, data protection]"}]}]}', true),
(gen_random_uuid(), NULL, 'adr', 'Architecture Decision Record', '{"type":"doc","content":[{"type":"heading","attrs":{"level":1},"content":[{"type":"text","text":"Architecture Decision Record"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Context"}]},{"type":"paragraph","content":[{"type":"text","text":"[What is the issue that motivates this decision?]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Considered Options"}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Option A: "}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Option B: "}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Decision"}]},{"type":"paragraph","content":[{"type":"text","text":"[What is the decision? Use the cover panel to set Status, Consequences, and record team votes.]"}]}]}', true),
(gen_random_uuid(), NULL, 'er_diagram', 'ER Diagram (Mermaid)', '{"type":"doc","content":[{"type":"heading","attrs":{"level":1},"content":[{"type":"text","text":"Entity-Relationship Diagram"}]},{"type":"codeBlock","attrs":{"language":"mermaid"},"content":[{"type":"text","text":"erDiagram\n    CUSTOMER ||--o{ ORDER : places\n    ORDER ||--|{ LINE-ITEM : contains\n    CUSTOMER {\n        string name\n        string email\n    }\n    ORDER {\n        int id\n        date created_at\n    }"}]}]}', true),
(gen_random_uuid(), NULL, 'api_spec', 'API Specification', '{"type":"doc","content":[{"type":"heading","attrs":{"level":1},"content":[{"type":"text","text":"API Specification"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Endpoints"}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"GET /v1/resource - List resources"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Request / Response Examples"}]},{"type":"codeBlock","attrs":{"language":"json"},"content":[{"type":"text","text":"{\n  \"id\": \"uuid\",\n  \"name\": \"example\"\n}"}]}]}', true),
(gen_random_uuid(), NULL, 'sequence_diagram', 'Sequence Diagram (Mermaid)', '{"type":"doc","content":[{"type":"heading","attrs":{"level":1},"content":[{"type":"text","text":"Sequence Diagram"}]},{"type":"codeBlock","attrs":{"language":"mermaid"},"content":[{"type":"text","text":"sequenceDiagram\n    participant Client\n    participant API\n    participant DB\n    Client->>API: POST /v1/resource\n    API->>DB: INSERT INTO resource\n    DB-->>API: row inserted\n    API-->>Client: 201 Created"}]}]}', true),
(gen_random_uuid(), NULL, 'tech_stack', 'Tech Stack Decision', '{"type":"doc","content":[{"type":"heading","attrs":{"level":1},"content":[{"type":"text","text":"Tech Stack Decision"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Rationale"}]},{"type":"paragraph","content":[{"type":"text","text":"[Why these choices?]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Alternatives Considered"}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Alternative: [name] - Rejected because: "}]}]}]}]}', true);

-- +goose Down
DELETE FROM document_template WHERE tenant_id IS NULL AND is_system = true;
DROP INDEX IF EXISTS template_system_type_name_uniq;
DROP INDEX IF EXISTS template_tenant_type_name_uniq;
ALTER TABLE document_template ADD CONSTRAINT document_template_tenant_id_type_name_key UNIQUE (tenant_id, type, name);
ALTER TABLE document_template ALTER COLUMN tenant_id SET NOT NULL;
DROP POLICY template_tenant_isolation ON document_template;
CREATE POLICY template_tenant_isolation ON document_template USING (tenant_id = current_tenant_uuid());
ALTER TABLE document DROP COLUMN metadata;
